spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: postgres
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
  logging:
    level:
      org:
        springframework:
          security: DEBUG

frontend:
  url: ${FRONTEND_URL}
